apiVersion: apps/v1
kind: Deployment
metadata:
  name: sar-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sar-gateway
  template:
    metadata:
      labels:
        app: sar-gateway
    spec:
      containers:
        - name: sar-gateway
          image: registry.gitlab.com/aditya-narayan-nayak/nisar_pro/sar-gateway:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: RUST_LOG
              value: "info"
            - name: ESA_USERNAME
              valueFrom:
                secretKeyRef:
                  name: esa-credentials
                  key: username
            - name: ESA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: esa-credentials
                  key: password
---
apiVersion: v1
kind: Service
metadata:
  name: sar-gateway-svc
spec:
  selector:
    app: sar-gateway
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
